### ISSUE TITLE
Feature request: Add additional game unlock setting to JSON

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/Tomb1Main#196] opened 2021-11-08 13:10 UTC
Having NG+ already unlocked in a fresh build of TR1M sends a bad signal to my eyes. I think it'd be more suitable to add:

Unlock all additional game modes - true/false

...to the JSON.

Let me know what you think.

**Comment by rr-** [comment] 2021-11-08 23:23
Alright

**Comment by thatguyfrombb** [comment] 2021-11-11 21:30
To whoever decides to develop this: If at all possible, make it skip the selection screen and act as if user picked standard new game. What I'm trying to avoid is having yet another option to test for standard new game which might end up acting differently.

**Comment by walkawayy** [comment] 2023-03-13 23:58
This already exists in `Tomb1Main_gameflow.json5` unless we think this should be added to the config tool?

**Comment by rr-** [comment] 2023-03-14 00:27
I agree, and I'd move crystal mode as well. And the draw distance.

However moving these settings to the config leaves a question on how to deal with custom level distribution as well as data duplication.

- If the setting is going to be copied - how to treat both values, the one in the config and the one in the gameflow?
- If the setting is going to be moved - sure enough, custom levels who wish to disable this can ship with the default config JSON. However I fear that a significant amount of players won't be bothered with configuring their keys the dev intended way and will just copy-paste their settings from a regular install, overriding the level author's choices. Do we care about that?

**Comment by walkawayy** [comment] 2023-03-14 00:29
That's a good point about custom levels. I'll think on it. And maybe we can ask some creators like Sabatu what their thoughts are.

**Comment by walkawayy** [comment] 2023-08-31 23:46
Closing as duplicate of #79.

**Closed by walkawayy** 2023-08-31 23:46 UTC
Labels: Feature, Easy first ticket
